### ISSUE TITLE
Using RGB instead of HSL on SVGs?

### ISSUE THREAD

**Issue by jounih** [harperreed/effigy.im#11]
Great work, very useful!

Small query - would it be possible to use RGB instead of HSL on SVGs? Two benefits:

1. Right now Figma or Illustrator can't parse the colours (HSL on SVG import not supported) - so they both show a black box when importing the generated SVGs
2. Slightly smaller file size - ie. rgb(86, 30, 63) instead of hsl(325,48.64401903003454%,22.80696037923917%) that is used currently

Thanks!

**Comment by harperreed** [comment]
Good update. Will investigate.
